apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: simple-djangoa-pp
        image: simple-djangoa-pp:latest
        ports:
        - containerPort: 8000
